# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Mod Properties
mod_version=1.2.0
maven_group=me.trruki
archives_base_name=map-coordinates

# Dependencies
# check this on https://fabricmc.net/develop
fabric_api_version=0.161.0+26.3
